apiVersion: v1
kind: Namespace
metadata:
  name: spiffe-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-demo-app
  namespace: spiffe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-demo-app
  template:
    metadata:
      labels:
        app: spiffe-demo-app
    spec:
      containers:
      - name: spiffe-demo-app
        image: ko.local/github.com/spirl/spiffe-demo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spiffe-demo-app-service
  namespace: spiffe-demo
spec:
  selector:
    app: spiffe-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer